[package]
name = "bubbledesk-wrapper"
version = "0.2.1"
edition = "2021"

[target.'cfg(windows)'.dependencies]
tauri-plugin-prevent-default = { version = "3", features = ["platform-windows"], optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24"
objc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging",
  "Win32_Foundation",
] }

[target.'cfg(target_os = "linux")'.dependencies]
image = "0.25"

[dependencies]
tauri = { version = "2", features = ["rustls-tls", "tray-icon", "devtools"] }
# Optional plugins (enable via Cargo features)
tauri-plugin-notification = { version = "2", optional = true }
tauri-plugin-autostart = { version = "2", optional = true }
tauri-plugin-global-shortcut = { version = "2", optional = true }
tauri-plugin-updater = { version = "2", optional = true }
tauri-plugin-persisted-scope = { version = "2", optional = true }
tauri-plugin-clipboard-manager = { version = "2", optional = true }
tauri-plugin-dialog = { version = "2", optional = true}
tauri-plugin-deep-link =  { version = "2", optional = true}
tauri-plugin-single-instance = { version = "2.3", features = ["deep-link"], optional = true }
tauri-plugin-prevent-default = { version = "3", optional = true }

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
walkdir = "2.5"
bytes = "1"
url = "2"
getrandom = "0.3.3"
chrono = { version = "0.4", features = ["clock"] }
zip = { version = "2", default-features = false, features = ["deflate"] }
tokio = "1.47.1"
reqwest = "0.12.23"
# Error handling
anyhow = "1.0"
# Async runtime già fornito da Tauri, qui serve solo std::thread
# ma se ti serve altrove puoi usare tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
# WASM runtime
wasmtime = "21.0"       # oppure la versione più recente stabile
# Abilita Preview1 altrimenti `WasiP1Ctx` non esiste
wasmtime-wasi = { version = "21", features = ["preview1"] }
# Per usare `wasi_common::sync::Dir::from_cap_std`
wasi-common = { version = "21", features = ["sync"] }
# Capability-based FS (per preopen sicuro)
cap-std = "3.4"
# Helpers
once_cell = "1.19"
rand = { version = "0.8", features = ["std", "std_rng"] }

[features]
default = [
    "tauri-plugin-notification",
    "tauri-plugin-autostart",
    "tauri-plugin-global-shortcut",
    "tauri-plugin-updater",
    "tauri-plugin-persisted-scope",
    "tauri-plugin-clipboard-manager",
    "tauri-plugin-dialog",
    "tauri-plugin-deep-link",
    "tauri-plugin-single-instance",
    "tauri-plugin-prevent-default",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[build-dependencies]
tauri-build = { version = "2", features = [] }
