[package]
name = "bubbledesk-wrapper"
version = "0.2.1"
edition = "2021"

[target.'cfg(windows)'.dependencies]
tauri-plugin-prevent-default = { version = "3", features = ["platform-windows"], optional = true }

[dependencies]
tauri = { version = "2", features = ["rustls-tls", "tray-icon", "devtools"] }
# Optional plugins (enable via Cargo features)
tauri-plugin-notification = { version = "2", optional = true }
tauri-plugin-autostart = { version = "2", optional = true }
tauri-plugin-global-shortcut = { version = "2", optional = true }
tauri-plugin-updater = { version = "2", optional = true }
tauri-plugin-persisted-scope = { version = "2", optional = true }
tauri-plugin-clipboard-manager = { version = "2", optional = true }
tauri-plugin-dialog = { version = "2", optional = true}
tauri-plugin-deep-link =  { version = "2", optional = true}
tauri-plugin-single-instance = { version = "2.3", features = ["deep-link"], optional = true }
tauri-plugin-prevent-default = { version = "3", optional = true }

serde = "1.0.219"
serde_json = "1"
base64 = "0.22"
walkdir = "2.5"
url = "2"
getrandom = "0.3.3"
chrono = { version = "0.4", features = ["clock"] }
zip = { version = "2", default-features = false, features = ["deflate"] }

[features]
default = [
    "tauri-plugin-notification",
    "tauri-plugin-autostart",
    "tauri-plugin-global-shortcut",
    "tauri-plugin-updater",
    "tauri-plugin-persisted-scope",
    "tauri-plugin-clipboard-manager",
    "tauri-plugin-dialog",
    "tauri-plugin-deep-link",
    "tauri-plugin-single-instance",
    "tauri-plugin-prevent-default",
]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[build-dependencies]
tauri-build = { version = "2", features = [] }
