type AnyFunc = (...args: any[]) => any;
type AsyncFunc = (...args: any[]) => Promise<any>;
type GenFunc = (...args: any[]) => Generator<any, any, any>;
interface Validate {
    string(v: unknown): v is string;
    url(v: unknown): v is string;
    nonEmptyString(v: unknown): v is string;
    number(v: unknown): v is number;
    integer(v: unknown): v is number;
    boolean(v: unknown): v is boolean;
    bigint(v: unknown): v is bigint;
    symbol(v: unknown): v is symbol;
    numeric(v: unknown): boolean;
    finiteNumber(v: unknown): v is number;
    dateString(v: unknown): v is string;
    date(v: unknown): v is Date;
    isoDateString(v: unknown): v is string;
    isoDateTimeString(v: unknown): v is string;
    null(v: unknown): v is null;
    undefined(v: unknown): v is undefined;
    defined<T>(v: T | null | undefined): v is T;
    nan(v: unknown): v is number;
    object(v: unknown): v is Record<string, unknown>;
    plainObject(v: unknown): v is Record<string, unknown>;
    emptyObject(v: unknown): v is Record<string, never>;
    array<T = unknown>(v: unknown): v is T[];
    nonEmptyArray<T = unknown>(v: unknown): v is T[];
    set<T = unknown>(v: unknown): v is Set<T>;
    map<K = unknown, V = unknown>(v: unknown): v is Map<K, V>;
    weakSet<T extends object = object>(v: unknown): v is WeakSet<T>;
    weakMap<K extends object = object, V = unknown>(v: unknown): v is WeakMap<K, V>;
    arrayBuffer(v: unknown): v is ArrayBuffer;
    dataView(v: unknown): v is DataView;
    typedArray(v: unknown): v is Exclude<ArrayBufferView, DataView>;
    regexp(v: unknown): v is RegExp;
    promise<T = unknown>(v: unknown): v is Promise<T>;
    function(v: unknown): v is AnyFunc;
    asyncFunction(v: unknown): v is AsyncFunc;
    generatorFunction(v: unknown): v is GenFunc;
    email(v: unknown): v is string;
    uuid(v: unknown): v is string;
    hexColor(v: unknown): v is string;
    ipv4(v: unknown): v is string;
    ipv6(v: unknown): v is string;
    jsonString(v: unknown): v is string;
    truthy(v: unknown): boolean;
    falsy(v: unknown): boolean;
}
export declare const validate: Validate;
export {};
